version: "3"
networks:
    analytics:
    redis:
services:
    webhook_server:
        build: .
        container_name: azmina-chatbot-webhook
        environment:
            PORT: ${PORT}
            TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
            TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
            TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
            TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}

            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}

            ANALYTICS_API_URL: ${ANALYTICS_API_URL}
            ANALYTICS_API_TOKEN: ${ANALYTICS_API_TOKEN}

            PENHAS_API_URL: ${PENHAS_API_URL}
            PENHAS_API_TOKEN: ${PENHAS_API_TOKEN}
        ports:
            - ${LAN_IP}:${EXPOSED_PORT}:${PORT}
        volumes:
            - ${HOST_MACHINE_LOG_DIR}:${LOG_DIR}
        networks:
            - analytics
            - redis

    redis:
        image: redis@sha256:442fbfdeccf203c277827cfd8e7e727ce411611e1a6caeda9cca8115ed17b9cc
        container_name: azmina-chatbot-redis
        networks:
            - redis
